# Generated by Django 3.2.6 on 2023-05-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20230510_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecentre',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.statename'),
        ),
    ]
